
name: Deployment

on:
  pull_request:
    branches:
      - "release/*"
      - "feature/*"
      - "master"
      - "develop"
    types: [closed]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        id: install
        run: yarn install

      - name: Generate schemas
        run: yarn run tsc:interface

      - name: Test code
        id: run-tests
        run: yarn run validate

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json

  build-version:
    needs: validate
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.generate-version.outputs.new-version }}
      branch: ${{ steps.generate-version.outputs.branch }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Generate new version
        id: generate-version
        uses: ./.github/actions/generate-version

  build:
    needs: build-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-version: ${{ steps.version.outputs.new-version }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Config Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Set new version in package.json
        id: version
        run: |
          NEW_VERSION=${{ needs.build-version.outputs.new-version }}
          echo "NEW_VERSION is $NEW_VERSION"
          echo "new-version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          npm version "$NEW_VERSION"

      - name: Install dependencies
        run: yarn install

      - name: Generate schemas
        run: yarn run tsc:interface

      - name: Build library
        run: yarn run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lib-files
          path: lib

      - name: Upload artifacts dist
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist